In [77]:
import numpy as np
import pandas as pd
from datetime import datetime

# %pip install openpyxl

In [ ]:
data.rename(columns={'In which country were you born?': 'Birth Country', 'In which city were you born?': 'Birth City',
                     'In which languages (spoken, not programming!) are you proficient? (Please list languages separated by commas). ': 'Languages Spoken' ,
                     'Which is your preferred OS?': 'Preferred OS' , 'Which is your preferred mobile OS?': 'Preferred Mobile OS' , '': '' , '': '' , '': '' , '': '' , '': '' , '': '' , '': '' , '': '' , '': '' , '': '' , '': '' })

In [ ]:
data['Whi']

In [33]:
data = pd.read_excel('hw-01-class-data.xlsx')
data

,In which country were you born?,In which city were you born?,"In which languages (spoken, not programming!) are you proficient? (Please list languages separated by commas).",Which is your preferred OS?,Which is your preferred mobile OS?,"What field(s) do you think can benefit the most from visualization? (If you have multiple answers, please separate them with a comma)",Please rank the animals you like most in the following list. [First Choice],Please rank the animals you like most in the following list. [Second Choice],Please rank the animals you like most in the following list. [Third Choice ],What is your favorite color?,What is your favorite number?,What temperature is it outside right now? (In Celsius),"On average, how many cups of coffee do you drink each day?",What time do you typically wake up?,What time do you typically go to bed?,What is your favorite visualization?
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,United States,"Los Angeles, California",English,Apple,Apple iOS,NaN,Flying squirrel,Dolphin,Cat,Blue,97,2,0,10:00:00,00:00:00,NaN
2,Netherlands,Haarlem,"Dutch, English",Windows,Apple iOS,Journalism,Sea Turtle,Hedgehog,Dog,Blue,8,1,1,08:00:00,12:00:00,I'm not sure. FiveThirtyEight.com does cool vi...
3,United States,"Rockville, Maryland","English, Korean",Windows,Apple iOS,Philosophy,Dolphin,Dog,Sea Turtle,Green,9,NaN,0.5,08:00:00,00:00:00,Pie Charts
4,United States,Warwick,English,Windows,Apple iOS,Finance,Dog,Elephant,Dolphin,Blue,3,3,1,09:00:00,01:00:00,Maps
5,United States,"Needham, MA",NaN,Apple,Apple iOS,Data Science,Hedgehog,Elephant,Llama,Blue,3,3,0,09:00:00,00:00:00,NaN
6,United States of America,Boston,English,Apple,Apple iOS,"Sports industry, health care, research",Elephant,Cat,Hedgehog,Green,8,2.2,0,09:00:00,00:00:00,Pie charts
7,India,Mumbai,"English, Hindi, Gujarati",Apple,Apple iOS,"Computer science, data analysis, finance, heal...",Dolphin,Cat,Elephant,Blue,7 and 2,2,0.5,08:00:00,22:00:00,Gravitational Waves by Science News
8,United States,Edison,English,Windows,Apple iOS,"Biology, Neurobiology, Buisness",Dog,Dolphin,Elephant,Green,13,3,1,09:00:00,23:30:00,Bar graph
9,US,NYC,"English, Chinese",Apple,Apple iOS,"research, biology, web development",Sea Turtle,Dolphin,Elephant,purple,72,2,1,09:00:00,00:30:00,maps

In [87]:
data.dtypes

In which country were you born?                                                                                                           object
In which city were you born?                                                                                                              object
In which languages (spoken, not programming!) are you proficient? (Please list languages separated by commas).                            object
Which is your preferred OS?                                                                                                               object
Which is your preferred mobile OS?                                                                                                        object
What field(s) do you think can benefit the most from visualization? (If you have multiple answers, please separate them with a comma)     object
Please rank the animals you like most in the following list.   [First Choice]                                                             object
Please rank the animals you like most in the following list.   [Second Choice]                                                            object
Please rank the animals you like most in the following list.   [Third Choice ]                                                            object
What is your favorite color?                                                                                                              object
What is your favorite number?                                                                                                            float64
What temperature is it outside right now? (In Celsius)                                                                                   float64
On average, how many cups of coffee do you drink each day?                                                                               float64
What time do you typically wake up?                                                                                                       object
What time do you typically go to bed?                                                                                                     object
What is your favorite visualization?                                                                                                      object
dtype: object

In [8]:
data.shape

(107, 16)

In [16]:
data.isnull().sum()

In which country were you born?                                                                                                           4
In which city were you born?                                                                                                              6
In which languages (spoken, not programming!) are you proficient? (Please list languages separated by commas).                            6
Which is your preferred OS?                                                                                                               4
Which is your preferred mobile OS?                                                                                                        4
What field(s) do you think can benefit the most from visualization? (If you have multiple answers, please separate them with a comma)    14
Please rank the animals you like most in the following list.   [First Choice]                                                             4
Please rank the animals you like most in the following list.   [Second Choice]                                                            4
Please rank the animals you like most in the following list.   [Third Choice ]                                                            4
What is your favorite color?                                                                                                              4
What is your favorite number?                                                                                                             4
What temperature is it outside right now? (In Celsius)                                                                                    6
On average, how many cups of coffee do you drink each day?                                                                                4
What time do you typically wake up?                                                                                                       4
What time do you typically go to bed?                                                                                                     4
What is your favorite visualization?                                                                                                     20
dtype: int64

In [25]:
# 26 rows with null
data[data.isnull().any(axis=1)].shape

(26, 16)

In [27]:
for col in data.columns:
    print(col)

In which country were you born?
In which city were you born?
In which languages (spoken, not programming!) are you proficient? (Please list languages separated by commas).
Which is your preferred OS?
Which is your preferred mobile OS?
What field(s) do you think can benefit the most from visualization? (If you have multiple answers, please separate them with a comma)
Please rank the animals you like most in the following list.   [First Choice]
Please rank the animals you like most in the following list.   [Second Choice]
Please rank the animals you like most in the following list.   [Third Choice ]
What is your favorite color?
What is your favorite number?
What temperature is it outside right now? (In Celsius)
On average, how many cups of coffee do you drink each day?
What time do you typically wake up?
What time do you typically go to bed?
What is your favorite visualization?

In [68]:
# lambda function to extract first number in a string
get_nums = lambda x: [float(num) for num in str(x).split() if num.isdigit()]
get_first_num_else_nan = lambda x: x[0] if len(x) > 0 else np.nan

In [48]:
# Problem row, change to just 7
# data[data['What is your favorite number?'] == '7 and 2']['What is your favorite number?'] = '7'
data['What is your favorite number?'].replace('7 and 2', '7', inplace=True)
data['What is your favorite number?'].replace('Don\'t have one.', np.nan, inplace=True)

# Change to floats
data['What is your favorite number?'] = data['What is your favorite number?'].astype(float)

In [60]:
# Change to lists of floats and then get first element if it exists
data['What temperature is it outside right now? (In Celsius) '] = data['What temperature is it outside right now? (In Celsius) '].apply(lambda x: [float(num) for num in str(x).split() if num.isdigit()])
data['What temperature is it outside right now? (In Celsius) '] = data['What temperature is it outside right now? (In Celsius) '].apply(lambda x: x[0] if len(x) > 0 else np.nan)

In [75]:
# Apply same lambda function to extract numbers
data['On average, how many cups of coffee do you drink each day?'].unique()
# data['On average, how many cups of coffee do you drink each day?'] = data['On average, how many cups of coffee do you drink each day?'].apply(get_nums)
# data['On average, how many cups of coffee do you drink each day?'] = data['On average, how many cups of coffee do you drink each day?'].apply(get_first_num_else_nan)

array([nan,  0.,  1.,  3.,  2.])

In [80]:
datetime(2008, 1, 1, 16, 0, 0)

datetime.datetime(2008, 1, 1, 16, 0)

In [88]:
data['What time do you typically go to bed? '].unique()

array([nan, datetime.time(0, 0), datetime.time(12, 0),
       datetime.time(1, 0), datetime.time(22, 0), datetime.time(23, 30),
       datetime.time(0, 30), datetime.time(23, 0), datetime.time(11, 30),
       datetime.time(1, 10), datetime.time(21, 0), datetime.time(2, 30),
       datetime.time(2, 0), datetime.time(1, 30), datetime.time(11, 0),
       datetime.time(5, 0), datetime.time(3, 0)], dtype=object)

In [101]:
data['What time do you typically go to bed? '].drop(index=0).unique()

array([datetime.time(0, 0), datetime.time(12, 0), datetime.time(1, 0),
       datetime.time(22, 0), datetime.time(23, 30), datetime.time(0, 30),
       datetime.time(23, 0), datetime.time(11, 30), nan,
       datetime.time(1, 10), datetime.time(21, 0), datetime.time(2, 30),
       datetime.time(2, 0), datetime.time(1, 30), datetime.time(11, 0),
       datetime.time(5, 0), datetime.time(3, 0)], dtype=object)

In [103]:
# drop rows that are all null/na

data.dropna(axis=0, how='all')

,In which country were you born?,In which city were you born?,"In which languages (spoken, not programming!) are you proficient? (Please list languages separated by commas).",Which is your preferred OS?,Which is your preferred mobile OS?,"What field(s) do you think can benefit the most from visualization? (If you have multiple answers, please separate them with a comma)",Please rank the animals you like most in the following list. [First Choice],Please rank the animals you like most in the following list. [Second Choice],Please rank the animals you like most in the following list. [Third Choice ],What is your favorite color?,What is your favorite number?,What temperature is it outside right now? (In Celsius),"On average, how many cups of coffee do you drink each day?",What time do you typically wake up?,What time do you typically go to bed?,What is your favorite visualization?
1,United States,"Los Angeles, California",English,Apple,Apple iOS,NaN,Flying squirrel,Dolphin,Cat,Blue,97.0,2.0,0.0,10:00:00,00:00:00,NaN
2,Netherlands,Haarlem,"Dutch, English",Windows,Apple iOS,Journalism,Sea Turtle,Hedgehog,Dog,Blue,8.0,1.0,1.0,08:00:00,12:00:00,I'm not sure. FiveThirtyEight.com does cool vi...
3,United States,"Rockville, Maryland","English, Korean",Windows,Apple iOS,Philosophy,Dolphin,Dog,Sea Turtle,Green,9.0,NaN,NaN,08:00:00,00:00:00,Pie Charts
4,United States,Warwick,English,Windows,Apple iOS,Finance,Dog,Elephant,Dolphin,Blue,3.0,3.0,1.0,09:00:00,01:00:00,Maps
5,United States,"Needham, MA",NaN,Apple,Apple iOS,Data Science,Hedgehog,Elephant,Llama,Blue,3.0,3.0,0.0,09:00:00,00:00:00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,Ethiopia,Addis Abeba,"English, Amharic",Windows,Apple iOS,I would be interested in using it for design,Elephant,Cat,Sea Turtle,Yellow,8.0,24.0,0.0,08:00:00,00:00:00,polls on map of USA
103,USA,Yonkers,"English, Korean",Windows,Apple iOS,I think data and business analysts can benefit...,Dog,Cat,Moose,Blue,11.0,NaN,0.0,10:00:00,03:00:00,Histogram
104,United States of America,Chicago,"English, Spanish","Use Apple a lot, but more versed on windows",Apple iOS,"Public Service, Finance, Tech",Cat,Dolphin,Flying squirrel,Red,8.0,NaN,NaN,08:00:00,01:00:00,"Object based, whether it be a map with specifi..."
105,India,Hyderabad,"English, Telugu",Apple,Apple iOS,"Marketing, Politcs",Llama,Cat,Elephant,Orange,21.0,NaN,NaN,11:00:00,02:30:00,The kobe bryant shot chart.
106,United States,Colorado Springs,Spanish,Windows,Apple iOS,"Machine Learning, Healthcare",Dog,Flying squirrel,Dolphin,Sunset orange,13.0,8.0,0.0,05:00:00,21:00:00,A mosaic

In [124]:
a1 = data['Please rank the animals you like most in the following list.   [First Choice]'].unique()
a2 = data['Please rank the animals you like most in the following list.   [Second Choice]'].unique()
a3 = data['Please rank the animals you like most in the following list.   [Third Choice ]'].unique()
np.concatenate([a1, a2, a3])

array([nan, 'Flying squirrel', 'Sea Turtle', 'Dolphin', 'Dog', 'Hedgehog',
       'Elephant', 'Llama', 'Cat', 'Moose', nan, 'Dolphin', 'Hedgehog',
       'Dog', 'Elephant', 'Cat', 'Llama', 'Sea Turtle', 'Flying squirrel',
       'Moose', nan, 'Cat', 'Dog', 'Sea Turtle', 'Dolphin', 'Llama',
       'Hedgehog', 'Elephant', 'Flying squirrel', 'Mouse', 'Moose'],
      dtype=object)

In [125]:
data['What is your favorite color?'].unique()

array([nan, 'Blue', 'Green', 'purple', 'green', 'Purple ', 'Rose gold ',
       'Red', 'Black', 'Pink', 'blue', 'grey', 'Baby blue', 'Purple',
       'Orange', 'navy', 'pink', 'Sage Green', 'I like all!', 'Yellow',
       'Navy', 'Pastel Mint', 'Light blue', 'Purpler', 'red', 'White',
       'Baby Pink', 'Cerulean', 'Pastel Mint Green', 'Sunset orange'],
      dtype=object)

In [107]:
data['Please rank the animals you like most in the following list.   [Third Choice ]'].unique()

array([nan, 'Cat', 'Dog', 'Sea Turtle', 'Dolphin', 'Llama', 'Hedgehog',
       'Elephant', 'Flying squirrel', 'Mouse', 'Moose'], dtype=object)